// Kalthoff-Winkler half-plate (symmetric about full-plate mid-plane)
// Generated by make_mesh_half.py. Units: mm, tonne, s, MPa.
// Graded refinement: h_crack in a corridor around the 70-deg lobe,
// h_coarse in the far field.

h_crack  = 0.25;
h_coarse = 5.0;
W  = 100.0;
H  = 100.0;
a  = 50.0;
yn = 25.0;
w  = 0.125;

// Corners
Point(1) = {0, 0, 0, h_coarse};          // bottom-left
Point(2) = {100.0, 0, 0, h_coarse};  // bottom-right
Point(3) = {100.0, 100.0, 0, h_coarse};  // top-right
Point(4) = {0, 100.0, 0, h_coarse};  // top-left

// Notch mouth + tip (fine spacing there)
Point(5) = {0, 24.875, 0, h_crack};                  // notch lower mouth
Point(6) = {0, 25.125, 0, h_crack};                  // notch upper mouth
Point(7) = {50.0, 24.875, 0, h_crack};     // tip lower
Point(8) = {50.0, 25.125, 0, h_crack};     // tip upper

// Contour (CCW): bottom -> right -> top -> left_top -> notch upper wall ->
// notch tip -> notch lower wall -> left_impact -> back to origin.
Line(1)  = {1, 2};   // bottom (symmetry)
Line(2)  = {2, 3};   // right
Line(3)  = {3, 4};   // top
Line(4)  = {4, 6};   // left_top (above notch mouth)
Line(5)  = {6, 8};   // notch upper wall
Line(6)  = {8, 7};   // notch tip
Line(7)  = {7, 5};   // notch lower wall
Line(8)  = {5, 1};   // left_impact (below notch mouth)

Curve Loop(1) = {1, 2, 3, 4, 5, 6, 7, 8};
Plane Surface(1) = {1};

// Graded refinement: fine mesh in a box around the expected 70-deg
// crack path from the notch tip (into the upper-right quadrant).
// Band width 2*l0 along the normal to the lobe, plus some margin.
Field[1] = Box;
Field[1].VIn  = h_crack;
Field[1].VOut = h_coarse;
Field[1].XMin = 49.5;
Field[1].XMax = 95.0;
Field[1].YMin = 15.0;
Field[1].YMax = 55.0;
Field[1].Thickness = 5;

Background Field = 1;

Physical Surface("plate")       = {1};
Physical Curve("bottom")        = {1};
Physical Curve("right")         = {2};
Physical Curve("top")           = {3};
Physical Curve("left_top")      = {4};
Physical Curve("notch")         = {5, 6, 7};  // upper wall + tip + lower wall
Physical Curve("left_impact")   = {8};

Mesh.Algorithm = 6;
Mesh.ElementOrder = 1;
Mesh.MeshSizeFromPoints = 1;
Mesh.MeshSizeFromCurvature = 0;
Mesh.MeshSizeExtendFromBoundary = 0;
