"""eta_residual canonical-default + scaffolder roundtrip tests.

Companion to ``tests/test_eta_residual_default_consistency.py`` (which
covers the runtime defaults shipped by PR #275 for issue #272). This
file extends that contract to the **scaffolder** (issue #276): every
YAML stub generated by ``scaffolder.generate_stub`` must round-trip
through the config loader with ``eta_residual == 1e-7`` -- i.e. it must
agree with both ``Material()`` and ``SolverSettings()`` defaults.

Why a separate file?
- The pre-existing test pins the runtime-API surface (Material and
  SolverSettings constructors). It is GREEN on ``main`` after PR #275.
- The scaffolder, however, kept emitting ``eta_residual: 1.0e-6`` in
  its YAML templates (``scaffolder.py:42, 59, 76`` pre-fix). A user
  scaffolding a fresh benchmark would silently re-introduce the 10x
  mismatch the W4 audit flagged. The tests below would FAIL on main
  pre-this-PR and PASS on the unified-default branch.

References
----------
- W4 audit: ``reports/SOLVER_BUGS_OPTIMISATION_AUDIT_2026-05-07.md``,
  T1.1 (eta_residual default mismatch).
- Issue #272 (HIGH bug, fixed in PR #275); Issue #276 (LOW follow-up,
  fixed in this PR).
- Canonical value: ``1e-7`` (Material's physics floor, see
  ``material.py:65``). Bourdin/Miehe convention is anywhere in
  ``[1e-6, 1e-9]``; the codebase has standardised on ``1e-7``.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest


# Canonical value pinned by PR #275 in ``material.py:65`` and
# ``config.py:365``. Any change here must be coordinated across all
# three sites (Material, SolverSettings, scaffolder).
CANONICAL_ETA_RESIDUAL = 1e-7


# ---------------------------------------------------------------------
# Single-source-of-truth assertions (defensive duplicates of the
# existing consistency test -- kept here so this file stands alone as
# the issue-276 acceptance gate even if the older test moves).
# ---------------------------------------------------------------------

def test_material_default_matches_canonical():
    """Material.eta_residual default is the canonical 1e-7."""
    from phast.material import Material
    assert Material().eta_residual == pytest.approx(CANONICAL_ETA_RESIDUAL)


def test_solver_default_matches_material_default():
    """SolverSettings.eta_residual default agrees with Material default."""
    from phast.config import SolverSettings
    from phast.material import Material
    assert SolverSettings().eta_residual == pytest.approx(Material().eta_residual)


# ---------------------------------------------------------------------
# Scaffolder template emits the canonical value (issue #276 core).
# ---------------------------------------------------------------------

@pytest.mark.parametrize(
    "solver_type", ["quasi_static", "static", "lbfgs"],
)
def test_scaffolder_template_emits_canonical_eta_residual(solver_type, tmp_path):
    """Each solver-type stub the scaffolder emits must contain the
    canonical ``eta_residual: 1.0e-7``. This is the exact-string check
    that pins the YAML template literal -- the template lives in
    ``scaffolder.SOLVER_DEFAULTS`` and is what users see when they edit
    a freshly-scaffolded benchmark.
    """
    from phast.scaffolder import generate_stub

    name = f"_eta_residual_test_{solver_type}"
    path = generate_stub(
        name=name,
        solver_type=solver_type,
        material="glass_borden",
        geometry="kalthoff_winkler",
        out_dir=str(tmp_path),
        validate=False,
    )
    text = Path(path).read_text()

    # The canonical scaffolder value, end-to-end:
    #   solver:
    #     ...
    #     eta_residual: 1.0e-7
    assert "eta_residual: 1.0e-7" in text, (
        f"Scaffolder for solver_type={solver_type!r} emitted YAML without "
        f"the canonical eta_residual: 1.0e-7. Output was:\n{text}"
    )

    # Negative: must NOT contain the legacy 1.0e-6 default any more
    # (this is the assertion that fails on ``main`` pre-PR).
    assert "eta_residual: 1.0e-6" not in text, (
        f"Scaffolder for solver_type={solver_type!r} still emits the "
        f"legacy eta_residual: 1.0e-6 default (issue #276)."
    )


# ---------------------------------------------------------------------
# Roundtrip: scaffolded YAML -> config loader -> SolverSettings agrees.
# ---------------------------------------------------------------------

@pytest.mark.parametrize(
    "solver_type", ["quasi_static", "static", "lbfgs"],
)
def test_scaffolder_yaml_roundtrips_with_canonical_eta_residual(
    solver_type, tmp_path
):
    """Generate a stub, parse it back via the production config loader,
    and verify ``cfg.solver.eta_residual`` matches the canonical value
    (== Material default, == SolverSettings default).
    """
    from phast.scaffolder import generate_stub
    from phast.config import load_config, SolverSettings
    from phast.material import Material

    path = generate_stub(
        name=f"_eta_residual_roundtrip_{solver_type}",
        solver_type=solver_type,
        material="glass_borden",
        geometry="kalthoff_winkler",
        out_dir=str(tmp_path),
        validate=False,
    )
    cfg = load_config(str(path))

    # The parsed config carries the canonical value.
    assert cfg.solver.eta_residual == pytest.approx(CANONICAL_ETA_RESIDUAL), (
        f"Scaffolded YAML for {solver_type!r} parsed to "
        f"cfg.solver.eta_residual = {cfg.solver.eta_residual!r}, "
        f"expected {CANONICAL_ETA_RESIDUAL}."
    )

    # Triple agreement: scaffold -> Material default -> SolverSettings default.
    assert cfg.solver.eta_residual == pytest.approx(Material().eta_residual)
    assert cfg.solver.eta_residual == pytest.approx(SolverSettings().eta_residual)


# ---------------------------------------------------------------------
# Anti-regression: the explicit scaffolder-internal table.
# ---------------------------------------------------------------------

def test_scaffolder_solver_defaults_table_uses_canonical_value():
    """Inspect ``scaffolder.SOLVER_DEFAULTS`` directly: every
    ``solver_block`` entry that mentions ``eta_residual`` must mention
    the canonical ``1.0e-7`` literal. ``explicit`` legitimately omits
    eta_residual (CFL-bounded solver, no static residual floor used).
    """
    from phast.scaffolder import SOLVER_DEFAULTS

    for solver_type, blocks in SOLVER_DEFAULTS.items():
        block = blocks.get("solver_block", "")
        if "eta_residual" not in block:
            # ``explicit`` solver type: legitimately omits.
            continue
        assert "eta_residual: 1.0e-7" in block, (
            f"SOLVER_DEFAULTS[{solver_type!r}]['solver_block'] does not "
            f"emit canonical eta_residual: 1.0e-7. Block was:\n{block}"
        )
        assert "eta_residual: 1.0e-6" not in block, (
            f"SOLVER_DEFAULTS[{solver_type!r}]['solver_block'] still "
            f"contains legacy eta_residual: 1.0e-6 (issue #276)."
        )
