#!/usr/bin/env python
"""Half-plate Kalthoff-Winkler mesh generator for torch + FEniCS two-way.

Canonical Kalthoff setup (Borden 2012 §4.3, PhaFiDyn convention):

    top (y=100) free
    ┌────────────────────────────┐
    │                            │  right (x=100) free
    │                            │
    │  notch (y=25)              │
    ├────────────────┤           │
    │                            │
    │ ← impact (v0 in +x)        │
    │                            │
    └────────────────────────────┘
    bottom (y=0) symmetry: u_y = 0

Upper half of the 100×200 mm full Kalthoff specimen with reflection
symmetry about the full-plate mid-plane. ONE notch at y = 25 mm
(= 125 - 100 in full-plate coords), length a = 50 mm from left edge.
Impact band at y ∈ [0, 25] mm on the left edge.

This half-plate variant is used for the §6.2 Kalthoff two-way
comparison (torch + FEniCS at spectral split). Akantu is excluded
because its ``phasefield quadratic`` class does not implement the
Miehe spectral split that Kalthoff requires — a custom C++ material
class extension would add it, and is the natural next contribution
from the EPFL Akantu team.

Graded refinement (PhaFiDyn-style, same pattern as ``examples/
dynamic_kalthoff_shear``): fine ``h_crack`` in a band around the
expected 70° propagation lobes from the notch tip, coarse
``h_coarse`` in the far field. Default: ``h_crack = 0.05`` mm (= l0/4
at l0 = 0.195 mm, Borden Fig 13 convergence), ``h_coarse = 5.0`` mm.

Physical group names match the full-plate ``make_mesh.py`` where
they map cleanly:

    bottom        (y = 0, symmetry)        — full-plate's 'bottom'
    top           (y = 100, free)          — full-plate's 'top'
    right         (x = 100, free)          — full-plate's 'right'
    left_impact   (x = 0, y ∈ [0, 25])     — full-plate's 'left_impact'
    left_top      (x = 0, y ∈ [25, 100])   — full-plate's 'left_top'
    notch         (upper notch walls+tip)  — full-plate's 'notch1'

(The full-plate groups ``left_bottom`` and ``notch2`` have no
half-plate analogue and are omitted; BC mapping in the torch and
FEniCS ports keys off ``notch`` rather than ``notch1``/``notch2``.)
"""
from __future__ import annotations

import argparse
import os


PLATE_W = 100.0            # mm, width
PLATE_H = 100.0            # mm, height (= half of full 200 mm)
NOTCH_LENGTH = 50.0        # mm
NOTCH_Y = 25.0             # mm, half-plate notch centreline (= 125 - 100)
NOTCH_THICKNESS = 0.25     # mm
L0_DEFAULT = 0.195         # canonical Kalthoff l0 (Borden 2012 §4.3)
H_CRACK_DEFAULT = 0.05     # = l0/4, matches Borden Fig 13 convergence


def _write_geo(geo_path: str, h_crack: float, h_coarse: float) -> None:
    w = NOTCH_THICKNESS / 2.0
    content = f"""\
// Kalthoff-Winkler half-plate (symmetric about full-plate mid-plane)
// Generated by make_mesh_half.py. Units: mm, tonne, s, MPa.
// Graded refinement: h_crack in a corridor around the 70-deg lobe,
// h_coarse in the far field.

h_crack  = {h_crack};
h_coarse = {h_coarse};
W  = {PLATE_W};
H  = {PLATE_H};
a  = {NOTCH_LENGTH};
yn = {NOTCH_Y};
w  = {w};

// Corners
Point(1) = {{0, 0, 0, h_coarse}};          // bottom-left
Point(2) = {{{PLATE_W}, 0, 0, h_coarse}};  // bottom-right
Point(3) = {{{PLATE_W}, {PLATE_H}, 0, h_coarse}};  // top-right
Point(4) = {{0, {PLATE_H}, 0, h_coarse}};  // top-left

// Notch mouth + tip (fine spacing there)
Point(5) = {{0, {NOTCH_Y - w}, 0, h_crack}};                  // notch lower mouth
Point(6) = {{0, {NOTCH_Y + w}, 0, h_crack}};                  // notch upper mouth
Point(7) = {{{NOTCH_LENGTH}, {NOTCH_Y - w}, 0, h_crack}};     // tip lower
Point(8) = {{{NOTCH_LENGTH}, {NOTCH_Y + w}, 0, h_crack}};     // tip upper

// Contour (CCW): bottom -> right -> top -> left_top -> notch upper wall ->
// notch tip -> notch lower wall -> left_impact -> back to origin.
Line(1)  = {{1, 2}};   // bottom (symmetry)
Line(2)  = {{2, 3}};   // right
Line(3)  = {{3, 4}};   // top
Line(4)  = {{4, 6}};   // left_top (above notch mouth)
Line(5)  = {{6, 8}};   // notch upper wall
Line(6)  = {{8, 7}};   // notch tip
Line(7)  = {{7, 5}};   // notch lower wall
Line(8)  = {{5, 1}};   // left_impact (below notch mouth)

Curve Loop(1) = {{1, 2, 3, 4, 5, 6, 7, 8}};
Plane Surface(1) = {{1}};

// Graded refinement: fine mesh in a box around the expected 70-deg
// crack path from the notch tip (into the upper-right quadrant).
// Band width 2*l0 along the normal to the lobe, plus some margin.
Field[1] = Box;
Field[1].VIn  = h_crack;
Field[1].VOut = h_coarse;
Field[1].XMin = {NOTCH_LENGTH - 2 * h_crack};
Field[1].XMax = {PLATE_W - 5};
Field[1].YMin = {NOTCH_Y - 10};
Field[1].YMax = {NOTCH_Y + 30};
Field[1].Thickness = 5;

Background Field = 1;

Physical Surface("plate")       = {{1}};
Physical Curve("bottom")        = {{1}};
Physical Curve("right")         = {{2}};
Physical Curve("top")           = {{3}};
Physical Curve("left_top")      = {{4}};
Physical Curve("notch")         = {{5, 6, 7}};  // upper wall + tip + lower wall
Physical Curve("left_impact")   = {{8}};

Mesh.Algorithm = 6;
Mesh.ElementOrder = 1;
Mesh.MeshSizeFromPoints = 1;
Mesh.MeshSizeFromCurvature = 0;
Mesh.MeshSizeExtendFromBoundary = 0;
"""
    with open(geo_path, "w") as f:
        f.write(content)


def _run_gmsh(geo_path: str, msh_path: str) -> None:
    import gmsh
    if not gmsh.isInitialized():
        gmsh.initialize()
    gmsh.option.setNumber("General.Verbosity", 0)
    gmsh.open(geo_path)
    gmsh.model.mesh.generate(2)
    gmsh.option.setNumber("Mesh.MshFileVersion", 2.2)
    gmsh.write(msh_path)
    gmsh.finalize()
    _ensure_ccw(msh_path)


def _ensure_ccw(msh_path: str) -> None:
    """Swap nodes 1 and 2 of every CW triangle (some gmsh options flip them)."""
    import meshio
    import numpy as np
    m = meshio.read(msh_path)
    changed = False
    for cb in m.cells:
        if cb.type != "triangle":
            continue
        pts = m.points[cb.data]
        v1 = pts[:, 1] - pts[:, 0]
        v2 = pts[:, 2] - pts[:, 0]
        cz = v1[:, 0] * v2[:, 1] - v1[:, 1] * v2[:, 0]
        cw_mask = cz < 0
        if cw_mask.any():
            cb.data[cw_mask] = cb.data[cw_mask][:, [0, 2, 1]]
            changed = True
    if changed:
        meshio.write(msh_path, m, file_format="gmsh22")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--h_crack", type=float, default=H_CRACK_DEFAULT,
                    help="Fine element size around the crack path "
                         "(default 0.05 mm = l0/4 at l0=0.195)")
    ap.add_argument("--h_coarse", type=float, default=5.0,
                    help="Far-field element size (default 5.0 mm)")
    ap.add_argument("--out", default=None,
                    help="Output .msh path (default: kalthoff_half_h<h_crack>.msh here)")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    msh_path = args.out or os.path.join(
        here, f"kalthoff_half_h{args.h_crack:g}.msh")
    geo_path = msh_path.replace(".msh", ".geo")

    _write_geo(geo_path, args.h_crack, args.h_coarse)
    _run_gmsh(geo_path, msh_path)

    import meshio
    m = meshio.read(msh_path)
    n_nodes = len(m.points)
    tri = [cb for cb in m.cells if cb.type == "triangle"]
    n_elems = len(tri[0].data) if tri else 0
    print(f"Wrote {msh_path}")
    print(f"  h_crack = {args.h_crack} mm, h_coarse = {args.h_coarse} mm")
    print(f"  {n_nodes} nodes, {n_elems} triangles")
    print(f"  half plate: {PLATE_W} x {PLATE_H} mm (upper half of 100x200 full)")
    print(f"  notch: y = {NOTCH_Y} mm, a = {NOTCH_LENGTH} mm, w = {NOTCH_THICKNESS} mm")
    print(f"  impact: x=0, y in [0, {NOTCH_Y - NOTCH_THICKNESS/2:.3f}]")
    print(f"  symmetry: u_y = 0 at y = 0")


if __name__ == "__main__":
    main()
